title: GitHub Blog
description: Simple blog powered by Jekyll and GitHub Pages.
theme: minima
lang: ko-KR
timezone: Asia/Seoul
url: "https://seokeon.github.io"
baseurl: "/github_blog"
markdown: kramdown
plugins:
  - jekyll-feed
